version: 2

models:
  - name: airports
    description: >
      List of Airports and their corresponding IATA code
    
  - name: airlines
    description: >
      List of Airlines and their corresponding ICAO code

  - name: hourly_flights
    description: >
      Hourly recorded flights in the bounded area with the corresponding Airline and origin and destination Ariport.
  
  - name: daily_flights
    description: >
      Recorded flights in the bounded area for the past 24 hours with the corresponding Airline and origin and destination Ariport.
